version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: splitwise
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    restart: always
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/splitwise
      JWT_SECRET: supersecretkey
      PORT: 4000
    depends_on:
      - db

volumes:
  postgres_data: